[Interface]
PrivateKey = MLB5pWnCBsuzgnP8Ad3hBVjrGbpo2bBeb++h0/VsoWs=
Address = 10.8.0.1/24
ListenPort = 27577
MTU = 1280
PostUp = iptables -A INPUT -i awg0 -j ACCEPT; iptables -A FORWARD -i awg0 -j ACCEPT; iptables -A OUTPUT -o awg0 -j ACCEPT; iptables -A FORWARD -i awg0 -o enp8s0 -s 10.8.0.1/ffffff00 -j ACCEPT; iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -A FORWARD -i enp8s0 -o awg0 -d 10.8.0.1/ffffff00 -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.8.0.1/ffffff00 -o enp8s0 -j MASQUERADE
PostDown = iptables -D INPUT -i awg0 -j ACCEPT; iptables -D FORWARD -i awg0 -j ACCEPT; iptables -D OUTPUT -o awg0 -j ACCEPT; iptables -D FORWARD -i awg0 -o enp8s0 -s 10.8.0.1/ffffff00 -j ACCEPT; iptables -D FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -D FORWARD -i enp8s0 -o awg0 -d 10.8.0.1/ffffff00 -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.8.0.1/ffffff00 -o enp8s0 -j MASQUERADE
Jc = 4
Jmin = 130
Jmax = 707
S1 = 43
S2 = 38
S3 = 3
S4 = 29
H1 = 118798367
H2 = 1273284763
H3 = 3056769501
H4 = 3944586310
I1 = <b 16><b fefd><b 0000><b 000000000000><b 0058><b 01><b 000054><b 0000><b 000000><b 000054><b fefd><t><r 28><b 00><b 00><b 0010><b cca8><b cca9><b cc02><b cc01><b 01><b 00>
I2 = <b 16><b fefd><b 0000><b 000000000000><b 0038><b 01><b 000034><b 0000><b 000000><b 000034><b fefd><t><r 28><b 00><b 00><b 0002><b cca8><b 01><b 00>
I3 = <b 16><b fefd><b 0000><b 000000000000><b 0028><b 01><b 000024><b 0000><b 000000><b 000024><b fefd><t><r 28><b 00><b 00><b 0002><b c00c><b 01><b 00>
I4 = <b 16><b fefd><b 0000><b 000000000000><b 0020><b 01><b 00001c><b 0000><b 000000><b 00001c><b fefd><t><r 28><b 00><b 00><b 0002><b 0000><b 01><b 00>
I5 = 
#_PSK = DFXVhjz41cfV9jx4DU6hisMJiEdCbUjgw0C8kGVMbh0=
